version: '2.2'
services:

  www:
    restart: always
    build: www/.
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db

  db:
    build: db/.
    environment:
      MYSQL_ROOT_PASSWORD: supersecure
    volumes:
      - database:/var/lib/mysql


volumes:
  database:            

