version: '2.4'
services:

  db:
    restart: always
    build: db/.
    environment:
      MYSQL_ROOT_PASSWORD: supersecure
    volumes:
      - database:/var/lib/mysql
   # healthcheck:
    #  test: "exit 0"


  www:
    restart: always
    build: www/.
    depends_on:
        db:
          condition: service_started
    ports:
      - "80:80"
  #  links:
  #    - db
     

volumes:
  database:            

