services:
  www:
    build: www/.
    ports:
      - "5000:5000" # HTTP port for testing
      #- "443:443" # HTTPS port for testing
    volumes:
      - /Users/rgm/certs:/etc/ssl/certs
    environment:
      - HTTPS_CERT=/etc/ssl/certs/localhost.crt
      - HTTPS_KEY=/etc/ssl/certs/localhost.key
  nginx:
    build: nginx/.   
    #image: nginx/.
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./nginx/mbp.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /Users/rgm/certs:/etc/ssl/certs
    depends_on:
      - www
    #environment:
    #  - NGINX_SERVER_NAME=localhost
      