services:
  www:
    build: www/.
    ports:
      - "5000:5000" # HTTP port for testing
      #- "443:443" # HTTPS port for testing
    volumes:
            #- /Users/rgm/certs:/etc/ssl/certs
      - ./www/.env:/opt/www/.env
    env_file:
      - ./www/mbp/.env
    environment:
      - HTTPS_CERT=/etc/ssl/certs/localhost.crt
      - HTTPS_KEY=/etc/ssl/certs/localhost.key
      #- SQLALCHEMY_DATABASE_URI=sqlite:///www/instance/site.db
      - SQLALCHEMY_TRACK_MODIFICATIONS=false
    #depends_on:
    #  - nginx
    # networks:
    #   - mbp_default
      
  nginx:
    build: nginx/.   
    #image: nginx/.
    ports:
      - "80:80"
      - "443:443"
    volumes:
            #- ./nginx/mbp.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/yakahu.com-0001/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/yakahu.com-0001/privkey.pem:/etc/nginx/ssl/privkey.pem
      #- /opt/certs:/etc/letsencrypt
        # networks:
    #   - mbp_default
    #depends_on:
    #  - www
    #environment:
    #  - NGINX_SERVER_NAME=localhost
      
