services:

  db:
    restart: always
    build: db/.
    environment:
      MARIADB_ROOT_PASSWORD: supersecure
    volumes: #averiguar las diferencias y ventajas comprado con el volume de abajo ./www:/opt/www
      - database:/var/lib/mysql

  www:
    restart: always
    build: www/.
    depends_on:
        db:
          condition: service_started
    volumes:
      - ./www:/opt/www
    env_file:
      - ./www/.env
    environment:
      FLASK_DEBUG: 0 #have the app run in debug mode. Change to 0 to turn OFF.
      #SECRET_KEY:
    ports:
      - '5000:5000'

  nginx:
    restart: always
    build: nginx/.
    depends_on:
      - www
    ports:
      - '80:80'
    volumes:
      - ./nginx/mbp.conf:/etc/nginx/conf.d/mbp.conf:ro


volumes:
  database:
  www: